version: '3.8'

services:
  backend:
    image: ghcr.io/darshan2224/devops-assignment/backend:latest
    container_name: devops-backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost  # Will be overridden in production
    restart: always

  frontend:
    image: ghcr.io/darshan2224/devops-assignment/frontend:latest
    container_name: devops-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000  # Will be overridden in production
    depends_on:
      - backend
    restart: always
